### ISSUE TITLE
offsets for iPhone 6S/iPhone 6S Plus iOS 11.3.1-11.2

### ISSUE THREAD

**Issue by razmashat** [Co2333/kernelCache#10]
11.3.1:
uint64_t ksym_vnode_lookup = 0xfffffff0071db710;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;
11.3:
(same as 11.3.1)
uint64_t ksym_vnode_lookup = 0xfffffff0071db710;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9a04;
11.2.6:
uint64_t ksym_vnode_lookup = 0xfffffff0071d6458;
uint64_t ksym_vfs_context_current = 0xfffffff0071f4864;
11.2.5:
(same as 11.2.6):
uint64_t ksym_vnode_lookup = 0xfffffff0071d6458;
uint64_t ksym_vfs_context_current = 0xfffffff0071f4864;
11.2.2;
uint64_t ksym_vnode_lookup = 0xfffffff0071d6528;
uint64_t ksym_vfs_context_current = 0xfffffff0071f4918;
11.2.1:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071d6528;
uint64_t ksym_vfs_context_current = 0xfffffff0071f4918;
11.2:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071d6528;
uint64_t ksym_vfs_context_current = 0xfffffff0071f4918;

**Comment by Co2333** [comment]
done
