### ISSUE TITLE
offsets for iPhone 6/iPhone 6 Plus iOS 11.3.1-11.2

### ISSUE THREAD

**Issue by razmashat** [Co2333/kernelCache#11]
11.3.1:
uint64_t ksym_vnode_lookup = 0xfffffff0071dff70;
uint64_t ksym_vfs_context_current = 0xfffffff0071ff918;
11.3: 
(same as 11.3.1)
uint64_t ksym_vnode_lookup = 0xfffffff0071dff70;
uint64_t ksym_vfs_context_current = 0xfffffff0071ff918;
11.2.6:
uint64_t ksym_vnode_lookup = 0xfffffff0071db3f0 ;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9874;
11.2.5:
(same as 11.2.6)
uint64_t ksym_vnode_lookup = 0xfffffff0071db3f0 ;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9874;
11.2.2:
uint64_t ksym_vnode_lookup = 0xfffffff0071db4c0 ;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9928;
11.2.1:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071db4c0 ;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9928;
11.2:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071db4c0 ;
uint64_t ksym_vfs_context_current = 0xfffffff0071f9928;

**Comment by Co2333** [comment]
Done
