### ISSUE TITLE
offsets for iPhone 5S GSM and Global iOS 11.3.1-11.2

### ISSUE THREAD

**Issue by razmashat** [Co2333/kernelCache#12]
11.3.1:
uint64_t ksym_vnode_lookup = 0xfffffff0071d3d08;
uint64_t ksym_vfs_context_current = 0xfffffff0071f2088;
11.3:
(same as 11.3.1)
uint64_t ksym_vnode_lookup = 0xfffffff0071d3d08;
uint64_t ksym_vfs_context_current = 0xfffffff0071f2088;
11.2.6:
uint64_t ksym_vnode_lookup = 0xfffffff0071cf1ac;
uint64_t ksym_vfs_context_current = 0xfffffff0071ed630;
11.2.5:
(same as 11.2.6)
uint64_t ksym_vnode_lookup = 0xfffffff0071cf1ac;
uint64_t ksym_vfs_context_current = 0xfffffff0071ed630;
11.2.2:
uint64_t ksym_vnode_lookup = 0xfffffff0071cf27c;
uint64_t ksym_vfs_context_current = 0xfffffff0071ed6e4;
11.2.1:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071cf27c;
uint64_t ksym_vfs_context_current = 0xfffffff0071ed6e4;
11.2.2:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff0071cf27c;
uint64_t ksym_vfs_context_current = 0xfffffff0071ed6e4;

**Comment by Co2333** [comment]
Done
