### ISSUE TITLE
iPad 6 (iPad 2018)11.3.1

### ISSUE THREAD

**Issue by razmashat** [Co2333/kernelCache#3]
uint64_t ksym_vnode_lookup = 0xffffffff007224de4;
uint64_t ksym_vfs_context_current = 0xfffffff0072430d8;

**Comment by Co2333** [comment]
how can I talk to you privately? I'd like to send you a copy that should works for your iPad.

**Comment by Co2333** [comment]
are you sure  about this????? the same as  iPhone 7

**Comment by razmashat** [comment]
checked again and  yeah same offsets don't know why

**Comment by Co2333** [comment]
All right.
