### ISSUE TITLE
 offsets for iPhone 8/iPhone 8 Plus GSM and Global iOS 11.3.1-11.2

### ISSUE THREAD

**Issue by razmashat** [Co2333/kernelCache#8]
11.3.1:
uint64_t ksym_vnode_lookup = 0xfffffff00722c0d0;
uint64_t ksym_vfs_context_current = 0xfffffff00724ae40;;
11.3: 
(same as 11.3.1)
uint64_t ksym_vnode_lookup = 0xfffffff00722c0d0;
uint64_t ksym_vfs_context_current = 0xfffffff00724ae40;
11.2.6:
uint64_t ksym_vnode_lookup = 0xfffffff007227f10;
uint64_t ksym_vfs_context_current = 0xfffffff007246940;
11.2.5:
(same as 11.2.5)
uint64_t ksym_vnode_lookup = 0xfffffff00721facc;
uint64_t ksym_vfs_context_current = 0xfffffff00723ded8;
11.2.2:
uint64_t ksym_vnode_lookup = 0xfffffff007227fe0;
uint64_t ksym_vfs_context_current = 0xfffffff0072469f4;
11.2.1:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff00721fb9c;
uint64_t ksym_vfs_context_current = 0xfffffff00723df8c;
11.2:
(same as 11.2.2)
uint64_t ksym_vnode_lookup = 0xfffffff00721fb9c;
uint64_t ksym_vfs_context_current = 0xfffffff00723df8c;

**Comment by Co2333** [comment]
thanks
