### ISSUE TITLE
NM command?

### ISSUE THREAD

**Issue by SeaJae** [Co2333/kernelCache#9]
Should the nm command be run on the MAC or on the iphone commandline?   the NM command is not found on the iphone commandline?

**Comment by razmashat** [comment]
Mac

**Comment by SeaJae** [comment]
Okay got this..  Iphone 8s IOS 11.3.1

$ joker -dec kernelcache \

mmapped: 0x124681000\
still HERE\
Feeding me a compressed kernelcache, eh? That's fine, now. I can decompress! \
Compressed Size: 16547780, Uncompressed: 33603584. Unknown (CRC?): 0x5e75853a, Unknown 1: 0x1\
Got kernel at 449\
got mem 0x12564b000\
mmapped: 0x12564b000\
This is a 64-bit kernel from iOS 11.x (b1+), or later (4570.52.2.0.0)\
ARM64 Exception Vector is at file offset @0xdd000 (Addr: 0xfffffff0070e1000)\


:After $ nm kernel | grep vfs_context_current #QAQ" nm /kernel | grep vnode_lookup #QAQ"\

fffffff00724ae40 S _vfs_context_current\

:After $ }

**Comment by razmashat** [comment]
already uploaded offsets for iPhone 8/iPhone 8 Plus but yeah looking good

**Comment by SeaJae** [comment]
Thanks!
